---
- hosts: centos
  tasks: 
    - name: Run ansible.sh
      command: /home/gatete/Desktop/ansible/Ansible-Deep-Dive/LXD
      async: 60
      poll: 0
      run_once: yes
    - name: Install mariadb
      package: 
        name: mariadb
        state: latest 
      become: yes
      
