---
- hosts: webservers
  become: yes
  vars_files:
    - /home/ansible/confidential
  tasks:
   - name: install httpd 
     yum:
      name: httpd
      state: latest
     notify: httpd service 
     tags: 
       - base-install
  handlers:
    - name: Restart and enable httpd
      services:
        name: httpd
        state: restarted
        enable: yes
      listen: httpd service 