---
- hosts: webservers
  become: yes
  vars_files:
    - /home/ansible/confidential
  tasks:
   - name: install httpd 
     yum:
      name: httpd
      state: latest
     notify: httpd service 
     tags: 
       - base-install
  handlers:
    - name: Restart and enable httpd
      services:
        name: httpd
        state: restarted
        enable: yes
      listen: httpd service 

    - name: configure virtual host
      template:
        src: /home/ansible/vhost.conf.j2
        dest: /etc/httpd/conf.d/vhost.conf
      notify: httpd service
      tags:
        - vhost
    - name: configure site auth
      template:
        src: /home/ansible/htpasswd.j2
        dest: /etc/httpd/conf/htpasswd
      notify: httpd service
      tags:
        - vhost
