--- 
- 
  become: true
  hosts: "apps ldb"
  tasks: 
    - 
      dest: /var/www/html/index.html
      mode: 511
      name: "install index"
      src: index.html.j2
      template: ~
  vars: 
    file_version: 1.0
